config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get "about", to: "static#about"
  get "contact", to: "static#contact"
  mount Sidekiq::Web => "/sidekiq"

  resources :episodes
  resources :podcasts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "podcasts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :podcast
  has_one_attached :media_file
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  has_many :episodes, dependent: :destroy

  validates :link, presence: true, uniqueness: true

  after_create :process_podcast

  def process_podcast
    CreatePodcastJob.perform_async(id)
  end

  def fetch_podcast
    url = link

    response = HTTParty.get(url)
    puts "trying to fetch #{url}"

    feed = Nokogiri::XML(response.body)
    podcast = feed.xpath("//channel").first

    # Build the Podcast object
    podcast_model = Podcast.where(link: link).first_or_initialize
    podcast_model.update(
      title: podcast.xpath("title").try(:text),
      description: podcast.xpath("description").try(:text),
      subtitle: podcast.xpath("itunes:subtitle").any? ? podcast.xpath("itunes:subtitle").text : nil,
      author: podcast.xpath("itunes:author").try(:text),
      image: podcast.xpath("itunes:image").any? ? podcast.xpath("itunes:image").attr("href").value : nil
    )

    # Save the Podcast instance
    podcast_model.save!

    # Loop through each item (episode) in the Podcast RSS feed
    podcast.xpath("//item").each do |episode|
      episode_model = Episode.new(
        podcast_id: podcast_model.id,
        title: episode.xpath("title").text,
        link: episode.at_xpath("enclosure/@url").try(:value),
        description: episode.xpath("description").text,
        published_at: episode.xpath("pubDate").text.to_datetime,
        guid: episode.xpath("guid").text
      )

      # Save the Episode instance
      episode_model.save!
    end

    podcast_model.processed = true
    podcast_model.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def admin?
    return if Rails.env.test?
    redirect_to root_path, alert: "You must be an admin to do that." # unless current_user.admin?
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: %i[show edit update destroy]

  # GET /episodes or /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1 or /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes or /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to episode_url(@episode), notice: "Episode was successfully created." }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1 or /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to episode_url(@episode), notice: "Episode was successfully updated." }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1 or /episodes/1.json
  def destroy
    @episode.destroy!

    respond_to do |format|
      format.html { redirect_to episodes_url, notice: "Episode was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_episode
    @episode = Episode.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def episode_params
    params.require(:episode).permit(:title, :link, :duration, :podcast_id, :description, :size, :published_at)
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: %i[show edit update destroy]
  before_action :admin?, only: %i[new edit update destroy]

  # GET /podcasts or /podcasts.json
  def index
    @podcasts = Podcast.all.reverse_order
  end

  # GET /podcasts/1 or /podcasts/1.json
  def show
    @episodes = @podcast.episodes
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts or /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to podcasts_url, notice: "Podcast was successfully created." }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { redirect_to podcasts_url, notice: "Error creating the podcast." }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1 or /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to podcast_url(@podcast), notice: "Podcast was successfully updated." }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1 or /podcasts/1.json
  def destroy
    @podcast.destroy!

    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: "Podcast was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def submit_podcast
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_podcast
    @podcast = Podcast.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def podcast_params
    params.require(:podcast).permit(:link)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/episodes/_episode.html.erb
<div class="card" id="<%= dom_id episode %>">
  <div class="row no-gutters">
    <div class="col-md-8">
      <div class="card-body">
        <p class="card-text"><%= episode.published_at %></p>
        <h5 class="card-title"><%= episode.title %></h5>
        <p class="card-text">
          <%= episode.description %>
        </p>
      </div>
    </div>
    <div class="col-md-2">
      <div class="card d-flex align-items-center justify-content-center">
        <div class="card-body">
          <h5 class="card-title"><%= episode.duration %></h5>
          <p class="card-text">Duration</p>
        </div>
      </div>
    </div>
    <div class="col-md-2">
      <div class="card d-flex align-items-center justify-content-center">
        <div class="card-body">
          <a href="<%= episode.link %>" class="btn btn-primary">Download</a>
        </div>
      </div>
    </div>
  </div>

app/views/episodes/_form.html.erb
<%= form_with(model: episode) do |form| %>
  <% if episode.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
        <% episode.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :podcast_id, style: "display: block" %>
    <%= form.text_field :podcast_id %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.number_field :size %>
  </div>

  <div>
    <%= form.label :published_at, style: "display: block" %>
    <%= form.datetime_field :published_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render "form", episode: @episode %>

<br>

<div>
  <%= link_to "Show this episode", @episode %> |
  <%= link_to "Back to episodes", episodes_path %>
</div>

app/views/episodes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Episodes</h1>

<div id="episodes">
  <% @episodes.each do |episode| %>
    <%= render episode %>
    <p>
      <%= link_to "Show this episode", episode %>
    </p>
  <% end %>
</div>

<%= link_to "New episode", new_episode_path %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render "form", episode: @episode %>

<br>

<div>
  <%= link_to "Back to episodes", episodes_path %>
</div>

app/views/episodes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @episode %>

<div>
  <%= link_to "Edit this episode", edit_episode_path(@episode) %> |
  <%= link_to "Back to episodes", episodes_path %>

  <%= button_to "Destroy this episode", @episode, method: :delete %>
</div>

app/views/layouts/application.html.erb
  <body>
  </body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Podcast Vault</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>
<body>
  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="/">
      <i class="fa fa-podcast" aria-hidden="true"></i>
      Podcast Vault
    </a>
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <a class="nav-link active" href="/about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>
    </ul>
  </nav>

  <%= yield %>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/podcasts/_add.html.erb
<%= form_with(model: podcast, class: "form-inline justify-content-center mt-3") do |form| %>
  <% if podcast.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
        <% podcast.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field(:link, class: "form-control mb-2 mr-sm-22", size: "64", placeholder: "Enter a podcast URL here . . .") %>
  </div>

  <div>
    <%= form.submit(class: "bt btn-primary mb-2") %>
  </div>
<% end %>

app/views/podcasts/_form.html.erb
<%= form_with(model: podcast) do |form| %>
  <% if podcast.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
        <% podcast.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/podcasts/_podcast.html.erb
<div id="<%= dom_id podcast %>">
  <p>
    <strong>Title:</strong>
    <%= podcast.title %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= podcast.link %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= podcast.description %>
  </p>

  <p>
    <strong>Subtitle:</strong>
    <%= podcast.subtitle %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= podcast.author %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= podcast.image %>
  </p>

</div>

app/views/podcasts/edit.html.erb
<h1>Editing podcast</h1>

<%= render "form", podcast: @podcast %>

<br>

<div>
  <%= link_to "Show this podcast", @podcast %> |
  <%= link_to "Back to podcasts", podcasts_path %>
</div>

app/views/podcasts/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container text-center">
    <h1 class="mt-5">Save Any Podcast Now</h1>
    <%= render "add", podcast: Podcast.new %>
</div>
<div class="container mt-5">
    <h1>Recently Added Podcasts</h1>
    <div class="row">
       <div id="podcasts" class="podcast-container">
        <% @podcasts.each do |podcast| %>
          <!-- Loop the card component -->
          <div class="podcast-item">
            <div class="">
              <img src="<%= podcast.image %>" class="card-img-top" alt="podcast">
              <div class="p-2">
                <h5 class="p-3"><%= podcast.title %></h5>
                <a href="<%= podcast_path(podcast) %>" class="btn btn-primary">View Podcast</a>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/podcasts/new.html.erb
<h1>New podcast</h1>

<%= render "form", podcast: @podcast %>

<br>

<div>
  <%= link_to "Back to podcasts", podcasts_path %>
</div>

app/views/podcasts/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <%= render @podcast %>
</div>
<div class="container">
   <% @episodes.each do |episode| %>
    <%= render episode %>
  <% end %>
</div>

<div>
  <%= link_to "Edit this podcast", edit_podcast_path(@podcast) %> |
  <%= link_to "Back to podcasts", podcasts_path %>

  <%= button_to "Destroy this podcast", @podcast, method: :delete %>
</div>